### ISSUE TITLE
Winnu flagship + NRA mech

### ISSUE THREAD

**Issue by darrellanderson** [darrellanderson/TI4-TTS#21]
NRA mech are ships when in the space area.  The current framework doesn't include the opponent units' modifiers when applying flagship mutations -- need to either one-off this case or pass more data to the mutation functions.

**Comment by darrellanderson** [comment]
Looking at it, it only gets the number of each unit type and not the unit data (with position).  This is not sufficient to determine ground vs space.

**Comment by Somberlord** [comment]
Is it fixed by this commit ? https://github.com/darrellanderson/TI4-TTS/commit/de3959e053ce0700613874182b2e19067863ae97

**Comment by darrellanderson** [comment]
Yes, thanks for the heads-up
