### ISSUE TITLE
propulsion research facility token shows tech side on Gral (with blue tech)

### ISSUE THREAD

**Issue by darrellanderson** [darrellanderson/TI4-TTS#28]
https://discord.com/channels/409096158372167683/410226691970039818/901080650415738920

**Comment by Somberlord** [comment]
I can't reproduce that bug. Token is always on the right side both on planet and card.

**Comment by darrellanderson** [comment]
Thanks.  I hadn't been able to reproduce it either (but just did a single test).  The attachment / decal script is pretty messy due to jamming in more and more features so might deserve a rethink, but will close this specific issue.
