### ISSUE TITLE
HCF on ground can't use Prophecy of Ixth

### ISSUE THREAD

**Issue by Somberlord** [darrellanderson/TI4-TTS#33]
When fighting on ground thanks to Matriarch, Prophecy of Ixth does not boost Hybrid Crystal Fighters hits.
The modifier is displayed, but the hit value is wrong. (1 more than space combat).

Morale Boost works fine.

It looks like Matriarch is applied with applyFlagshipModifiers(), but not in the CHOOSE part of applyUnitModifiers(). And only in ground combat...

**Comment by darrellanderson** [comment]
Thanks for the detailed report, fixed in the above change.  Should go out with the next mod update.
